quarkus:
  mongodb:
    credentials:
      username: admin
      password: adminpassword
    connection-string: mongodb://localhost:27017/rinha
    # Disable MongoDB authentication if needed
    # credentials-disabled: true
